### ISSUE TITLE
Create new input fields based on relevant info

### ISSUE THREAD

**Issue by alice-nie** [CMU-313/fall22-hw3-team-duquesne#9]
Based on the prototype built from #4, we need to create the same fields and field names in the frontend. This includes getting rid of the old metadata fields and syncing up variable names with the other stacks for consistency. Creating the new fields should mean that the document page has the correct number of fields and the correct labels.

**Estimated time:** 1 hour
_Justification: Ran was in charge of frontend in the previous assignment, so she knows where the files are allocated and which elements to update. Workload will be based on how much metadata to delete/add._

**Frontend Acceptance Criteria:** 
The website page contains all the fields specified in the prototype. All the interactive fields respond correctly with user input.

**Comment by LunaFang1016** [comment]
The original document edit page of Teedy does not contain relevant entries that fit a graduate student application system.
We need to reformat the form to get rid of irrelevant data and include useful ones.
We are going to make the following changes in the user interface (* refers to required inputs):
Primary Metadata --> Student data
Title --> Name*
Add: Gender
Add: Country
Add: Race
Creation Date --> Application Date*
Upload File --> Resume
Description --> Additional Notes
Tags
Additional Metadata --> Academic History
Add: Undergrad University*
Add: Desired Program*
Add: Major*
Add: Minor
Add: GPA*
Add: MCAT
Add: LSAT
Add: GRE
Add: MCAT
Delete: All current additional metadata rows

Prototype:
![prototype](https://user-images.githubusercontent.com/105766629/194405699-796e6a74-18c2-40ab-8c71-be95b86e6050.png)

**Comment by alice-nie** [comment]
Resolved by #2
